kafka:
  image: bitnami/kafka:3.5
  container_name: kafka
  ports:
    - "9092:9092"
  environment:
    - KAFKA_BROKER_ID=1
    - KAFKA_ZOOKEEPER_CONNECT=localhost:2181   # your Zookeeper host:port
    - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    - ALLOW_PLAINTEXT_LISTENER=yes
